### ISSUE TITLE
Please implement the ability to change the file name when downloading.

### ISSUE THREAD

**Issue by kamitsu2004** [Bluegrams/Vividl#102] opened 2023-09-24 21:43 UTC
When downloading an m3u8 file, it will be a random alphabet such as 'abcde'.
It is a hassle to change the file name after each download, so I would like to be able to specify the file name in advance.
Please consider this.

**Comment by alxnull** [comment] 2024-01-02 16:31
Duplicate of #49. Currently in work.

**Closed by alxnull** 2024-01-02 16:31 UTC
Labels: duplicate
