### ISSUE TITLE
Don't launch the program

### ISSUE THREAD

**Issue by xetrin** [Bluegrams/Vividl#7] opened 2020-04-26 01:23 UTC
Edition: Windows 10 Pro
Version: 1909
OS build: 18363.778

**Comment by alxnull** [comment] 2020-04-26 08:25
Which version of Vividl are you using? Does a file containing error information exist under `%temp%\vividl.log`? If yes, please add the content here.

**Comment by xetrin** [comment] 2020-04-26 12:36
I used version 0.2.1 portable and full. They not worked.

This is log:
`[2020-04-26 03:59] An unhandled exception caused the application to terminate unexpectedly.
System.ArgumentException: Не удалось создать свойство 'Left'  из значения по умолчанию. Сообщение об ошибке: не число не является допустимым значением для 'Double'.
   в System.Configuration.SettingsPropertyValue.Deserialize()
   в System.Configuration.SettingsPropertyValue.get_PropertyValue()
   в System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   в System.Configuration.SettingsBase.get_Item(String propertyName)
   в Bluegrams.Application.WpfWindowManager.ContextLoad()
   в lambda_method(Closure , Object , RoutedEventArgs )
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   в System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   в System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   в MS.Internal.LoadedOrUnloadedOperation.DoWork()
   в System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   в System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   в System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   в System.Windows.Interop.HwndTarget.OnResize()
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
[2020-04-26 03:59] An unhandled exception caused the application to terminate unexpectedly.
System.ArgumentException: Не удалось создать свойство 'Left'  из значения по умолчанию. Сообщение об ошибке: не число не является допустимым значением для 'Double'.
   в System.Configuration.SettingsPropertyValue.Deserialize()
   в System.Configuration.SettingsPropertyValue.get_PropertyValue()
   в System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   в System.Configuration.SettingsBase.get_Item(String propertyName)
   в Bluegrams.Application.WpfWindowManager.ContextLoad()
   в lambda_method(Closure , Object , RoutedEventArgs )
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   в System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   в System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   в MS.Internal.LoadedOrUnloadedOperation.DoWork()
   в System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   в System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   в System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   в System.Windows.Interop.HwndTarget.OnResize()
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
[2020-04-26 04:00] An unhandled exception caused the application to terminate unexpectedly.
System.ArgumentException: Не удалось создать свойство 'Left'  из значения по умолчанию. Сообщение об ошибке: не число не является допустимым значением для 'Double'.
   в System.Configuration.SettingsPropertyValue.Deserialize()
   в System.Configuration.SettingsPropertyValue.get_PropertyValue()
   в System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   в System.Configuration.SettingsBase.get_Item(String propertyName)
   в Bluegrams.Application.WpfWindowManager.ContextLoad()
   в lambda_method(Closure , Object , RoutedEventArgs )
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   в System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   в System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   в MS.Internal.LoadedOrUnloadedOperation.DoWork()
   в System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   в System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   в System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   в System.Windows.Interop.HwndTarget.OnResize()
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
[2020-04-26 04:06] An unhandled exception caused the application to terminate unexpectedly.
System.ArgumentException: Не удалось создать свойство 'Left'  из значения по умолчанию. Сообщение об ошибке: не число не является допустимым значением для 'Double'.
   в System.Configuration.SettingsPropertyValue.Deserialize()
   в System.Configuration.SettingsPropertyValue.get_PropertyValue()
   в System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   в System.Configuration.SettingsBase.get_Item(String propertyName)
   в Bluegrams.Application.WpfWindowManager.ContextLoad()
   в lambda_method(Closure , Object , RoutedEventArgs )
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   в System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   в System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   в MS.Internal.LoadedOrUnloadedOperation.DoWork()
   в System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   в System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   в System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   в System.Windows.Interop.HwndTarget.OnResize()
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
[2020-04-26 04:24] An unhandled exception caused the application to terminate unexpectedly.
System.ArgumentException: Не удалось создать свойство 'Left'  из значения по умолчанию. Сообщение об ошибке: не число не является допустимым значением для 'Double'.
   в System.Configuration.SettingsPropertyValue.Deserialize()
   в System.Configuration.SettingsPropertyValue.get_PropertyValue()
   в System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   в System.Configuration.SettingsBase.get_Item(String propertyName)
   в Bluegrams.Application.WpfWindowManager.ContextLoad()
   в lambda_method(Closure , Object , RoutedEventArgs )
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   в System.Windows.BroadcastEventHelper.BroadcastEvent(DependencyObject root, RoutedEvent routedEvent)
   в System.Windows.BroadcastEventHelper.BroadcastLoadedEvent(Object root)
   в MS.Internal.LoadedOrUnloadedOperation.DoWork()
   в System.Windows.Media.MediaContext.FireLoadedPendingCallbacks()
   в System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   в System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   в System.Windows.Media.MediaContext.Resize(ICompositionTarget resizedCompositionTarget)
   в System.Windows.Interop.HwndTarget.OnResize()
   в System.Windows.Interop.HwndTarget.HandleMessage(WindowMessage msg, IntPtr wparam, IntPtr lparam)
   в System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   в System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.DefWndProcWrapper(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.UnsafeNativeMethods.CallWindowProc(IntPtr wndProc, IntPtr hWnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   в MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
`

**Comment by xetrin** [comment] 2020-04-26 12:42
Oh yes... Windows 64-bit)

**Comment by alxnull** [comment] 2020-04-26 14:00
I think I have found the cause of your issue from the log you posted. I will fix this bug in the next version.

Until fixed, please try this workaround:
1. Use the latest portable version
2. In the program folder, there should be a file `portable.config` (if not, please try to start the app once more); open it for edit
3. In this file, add the following *directly after* the section `<Bluegrams.Application.Properties.Settings> ... </Bluegrams.Application.Properties.Settings>`:

```
<Bluegrams.Application.CustomSettings>
  <Width>600</Width>
  <Height>400</Height>
  <Left>100</Left>
  <Top>100</Top>
  <WindowState>Normal</WindowState>
</Bluegrams.Application.CustomSettings>
```
If you tried this, please report back if it worked. Thanks!

**Comment by xetrin** [comment] 2020-04-26 14:59
I edited `portable.config` and the portable version started up. Thanks you!

**Comment by alxnull** [comment] 2020-05-03 12:17
Fix released in v.0.2.2.

**Closed by alxnull** 2020-05-03 12:17 UTC
Labels: bug
