### ISSUE TITLE
Logs popping up on the screen

### ISSUE THREAD

**Issue by nero1st** [Bluegrams/Vividl#9] opened 2020-05-01 19:56 UTC
Hi!
Firstly I would like to say thank you for this pretty nice tool that makes using youtube-dl much simpler! 😄 

So, the reason for this issue is not exactly a bug or error, but a suggestion.

As you can see below, apparently when it is necessary to use FFmpeg to merge the parts of the video while downloading, the entire event log is shown on the screen as "warning" messages.
![Vividl](https://user-images.githubusercontent.com/42862510/80834320-df0a4880-8bc6-11ea-995a-ce28269267af.png)

In my opinion, it makes the interface a little bit polluted, and this spam of warnings can be kind of scary for users. If I may suggest a tab for them or something would be great. 😉
What do you think?

Thanks for reading!

**Comment by alxnull** [comment] 2020-05-01 22:22
Thanks for reporting!
This bunch of warnings from ffmpeg definitely is not the way it should look like. From your picture, it seems ffmpeg is running with a high verbosity level. However, I could not reproduce this on my side for the moment. Are you using the youtube-dl and ffmpeg versions provided with this app? Have you set some custom configuration fro ffmpeg etc.?

**Comment by nero1st** [comment] 2020-05-01 23:53
To reproduce is simple:
All you have to do is use any Crunchyroll stream link. (Or any other site that delivers the stream in parts)

In the image example, I've used this one:
https://www.crunchyroll.com/en-gb/tower-of-god/episode-4-the-green-april-794522

And yes, youtube-dl and FFmpeg I'm using are the ones that came with the app.
The parameters that appear in the image are the default settings of FFmpeg; I haven't changed anything. It also happens if you use youtube-dl from the command line, probably because FFmpeg is called to merge the parts of the stream while downloading.

**Comment by alxnull** [comment] 2020-05-02 16:44
I made a fix that should prevent the ffmpeg error output to show up as warnings in the UI. Will be released with the next update.

Thanks again for your feedback! 👍

**Comment by alxnull** [comment] 2020-05-03 12:36
Fix released in v.0.2.2.

**Closed by alxnull** 2020-05-03 12:36 UTC
Labels: bug
