### ISSUE TITLE
Application Settings Not Persisting

### ISSUE THREAD

**Issue by hl2guide** [Bluegrams/Vividl#92] opened 2023-04-30 23:49 UTC
Application settings don't persist between application launches.

e.g. set the app theme to dark, close off the app, start again, the theme is white.

**Comment by Praeses0** [comment] 2023-05-14 12:09
I'm facing the same issue as well. 
None of the settings persist.

I'm using v0.7.1 on Windows

**Comment by alxnull** [comment] 2023-05-14 16:58
Hey, thanks for reporting this. Could you share which variant of Vividl you're using, i.e. with installer, portable version or via chocolate? Thanks!

**Comment by Praeses0** [comment] 2023-05-14 17:48
I tried both with the installer and via chocolatey

**Comment by alxnull** [comment] 2023-05-14 18:06
Ok, currently I'm unable to reproduce this issue on my side. Usually, the settings for these variants should be preserved to the AppData folder. To check if that's maybe not happening, could you go to `%APPDATA%/Bluegrams`, then look for a folder starting with `Vividl.exe` and check if that folder contains a folder `0.7.1.0` with a `user.config` file. If that's the case, please check whether that file is not empty. Thanks!

**Comment by hl2guide** [comment] 2023-05-14 23:34
@alxnull 

For me I have two configs in both `Local` and `Roaming` folders.

```
C:\Users\Dean\AppData\Local\Bluegrams\Vividl.exe_Url_rz0pmv2lcv045rn4xnj5fqo5wqolmo43\0.7.1.0
C:\Users\Dean\AppData\Roaming\Bluegrams\Vividl.exe_Url_rz0pmv2lcv045rn4xnj5fqo5wqolmo43\0.7.1.0
```

The `user.config` file contains:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <configSections>
        <sectionGroup name="userSettings">
            <section name="Bluegrams.Application.UpdateCheckerBase" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false" />
        </sectionGroup>
    </configSections>
    <userSettings>
        <Bluegrams.Application.UpdateCheckerBase>
            <setting name="SkipVersion" serializeAs="String">
                <value>False</value>
            </setting>
        </Bluegrams.Application.UpdateCheckerBase>
    </userSettings>
</configuration>
```

**Comment by as-muncher** [comment] 2023-05-16 02:57
I found that some of my settings had to be set again after I upgraded from 0.7 to 0.7.1.

**Comment by fourteen-1** [comment] 2023-05-20 15:08
Looks like I'm facing the same issue. **No settings** are saved on exit. The app just "resets" to default (putting reset in quotes because I think a crash is happening on app exit which is preventing it from saving the changes). I have tried it with both .msi and portable zip and the bug exists in both versions. 

![vividlNOSETTINGSSAVEBUG (4)](https://github.com/Bluegrams/Vividl/assets/73333396/9d838ec1-066b-492f-a840-30541a1761b0)

**Comment by alxnull** [comment] 2023-05-21 09:32
Thank you all for adding details on this! I identified an issue that's prevents settings from being correctly saved when closing the application via `File -> Exit` (or `Alt+F4`) and will fix this. They should be saved correctly however when closing via "X".

**Comment by fourteen-1** [comment] 2023-05-21 14:21
thanks for providing with the closing via "X" alternative. It's saving settings now, *however*, the "Directly Download Videos" feature in Advanced settings does not remain toggled on after a restart still. 

[Additional (& off-topic-ish) info] I'm not sure what the "Directly Download Videos" feature does since I cant get it to stay enabled. But I am trying to have the app set in a way where I can "Ctrl+V" the video URL into the app and have the app start download (without the additional need to wait until the video info loads in and having to press the download button). Is what I am describing done by this feature? If not I would like to propose a feature request for this functionality.

**Closed** 2023-05-23 07:44 UTC
Labels: bug

**Comment by alxnull** [comment] 2023-07-01 21:21
@fourteen-1 re the "Directly Download Videos" feature: This is related to the automation feature which allows you to directly fetch & download any video urls copied to your clipboard without explicitly pasting them to the app. This feature can be activated via "Automate -> Auto-import URLs from Clipboard" in the main menu.

If this is not the feature you wanted, please open a feature request in a new issue.
